### ISSUE TITLE
maze data

### ISSUE THREAD

**Issue by outshine-J** [episodeyang/e-maml#2]
Can you provide the maze data? Includes mazes_10k_10x10.npz, mazes_10k_20x20.npz, and mazes_test_10k_20x20.npz. Or where can I find this data. thanks.

**Comment by geyang** [comment]
Hey @outshine-J  I took a quick look on my laptop, and it looks like the code is now lost.

The maze generation code is relatively simple. You can take a look at this post and the following repos on GitHub

- [Fun with Mazes](https://medium.com/swlh/fun-with-python-1-maze-generator-931639b4fb7e)
- [Maze-generator | GitHub](https://github.com/topics/maze-generator?l=python)

This codebase is **four years old** now. And finally, TensorFlow is dead!
